version: "3"
services:
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: Rtrhys331
      MYSQL_USER: Slase
      MYSQL_PASSWORD: Rtrhys331
    ports:
      - "3306:3306"

  back:
    build: ./back
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./back:/api
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db:mysql

  front:
    build: ./front
    command: /bin/sh -c "yarn serve --mode development"
    volumes:
      - ./front:/app
      # - frontend-node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - back
    tty: true
