version: "3"
services:
  front:
    build: ./front
    command: /bin/sh -c "npm run serve"
    volumes:
      - ./front:/app
      # - frontend-node_modules:/app/node_modules
    ports:
      - "8080:8080"
    tty: true
